### PR TITLE
Add InternshipApplication and Status

### PR DESCRIPTION
**Pull request by ongch00**

### CODE REVIEW

**Comment by ongch00** [comment]
This should be sufficient for us to start refactoring with. Let me know if something is wrong. We will merge when everyone has reviewed and commented on it.

**Comment by gerhean** [comment]
Good job

**Comment by FeliciaTay** [comment]
Looks good to me!

**Comment by foochifa** [comment]
Thanks for putting in all the javadocs! Looks great!

**Comment by wxwxwxwx9** [comment]
Looks good. Thanks CH!

**Pull request merged**
