### PR TITLE
Interview display overhaul

### LINKED ISSUE #141: Internship still displayed after list changes
Screenshot_21
I dunno if this is bug or intended 'feature'. Just gonna leave this here anyway.

### LINKED ISSUE #170: [PE-D] Last selected internship remains on right pane after using the "clear" command
Commands used:
1. `select 2`
2. `clear`, followed by `yes`

After using the "select" command to view internship application, use the "clear" command. The last selected application is still visible on the right pane. Shown below.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kevinswk94/ped#1

### PR DESCRIPTION
**Pull request by gerhean**
Dont PR until tests added.

### CODE REVIEW

**Comment by gerhean** [comment]
Tests added.

**Comment by foochifa** [comment]
Thanks GH, it looks good! However, with this implementation, the display will only be generated by select command right? Do you think it will be good if other commands that modifies an IA will display it too? Like in Add/Edit/Interview, as that was my original consideration.

**Comment by gerhean** [comment]
Add and Edit already displays the internship. Forgot about interview.

**Comment by foochifa** [comment]
No problem then, as its my command I can fix that. Then shall I merge this PR?

**Comment by gerhean** [comment]
Sure

**Pull request merged**
